AWSTemplateFormatVersion: "2010-09-09"

Description: A template that creates autoscalegroup and elb

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.nano
    Description: Enter t2.micro or t2.nano. Default is t2.micro.

  ImageId:
    Type: String
    Default: ami-06c68f701d8090592
    AllowedValues:
      - ami-06c68f701d8090592
      - ami-04a81a99f5ec58529
    Description: Enter Amazon Linux (ami-06c68f701d8090592) or Ubuntu (ami-04a81a99f5ec58529). Amazon Linux is default.

Resources:
  WebLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref ImageId 
      InstanceType: !Ref InstanceType
      LaunchConfigurationName: WebserverConfiguration
      SecurityGroups: 
        - sg-1234
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum update -y
          yum install -y httpd.x86_64
          systemctl start httpd.service
          systemctl enable httpd.service
          usermod -a -G apache ec2-user
          chown -R ec2-user:apache /var/www
          chmod 2775 /var/www
          find /var/www -type d -exec chmod 2775 {} \;
          find /var/www -type f -exec chmod 0664 {} \;
          echo "hello world from ${AWS::Region}" > /var/www/html/index.html

  WebAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      DesiredCapacity: 2
      LaunchConfigurationName: !Ref WebLaunchConfiguration
      MaxSize: 2
      MinSize: 1
      VPCZoneIdentifier:
        - subnet-111
        - subnet-222
      AvailabilityZones: 
        - us-east-1a
        - us-east-1c
      TargetGroupARNs: 
        - !Ref AppLoadBalancerTargetGroup

  AppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Subnets:
        - subnet-111
        - subnet-222
      Type: application


  AppLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref AppLoadBalancerTargetGroup
      LoadBalancerArn: !Ref AppLoadBalancer
      Port: 80
      Protocol: HTTP

  AppLoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: vpc-0001
      TargetType: instance

# CloudWatch

  HostedZoneCloudWatchLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1
      LogGroupName: /aws/route53/webapp

# SNS
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: Alerts

  MySNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref MySNSTopic
      Endpoint: your@example.com
      Protocol: email


# Route 53

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: mydummywebsite.com.
      QueryLoggingConfig:
        CloudWatchLogsLogGroupArn: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/route53/webapp'

# Resource Records

  MyResourceRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: HostedZone
    Properties:
      TTL: '900'
      HostedZoneName: mydummywebsite.com.
      Name: blog.mydummywebsite.com.
      Type: CNAME
      ResourceRecords:
        - !GetAtt AppLoadBalancer.DNSName

  MyLogPolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: "LogResourcePolicy"
      PolicyDocument: !Sub  "{ \"Version\": \"2012-10-17\", \"Statement\": [ { \"Sid\": \"Route53LogsToCloudWatchLogs\", \"Effect\": \"Allow\", \"Principal\": { \"Service\": [ \"route53.amazonaws.com\" ] }, \"Action\":[\"logs:CreateLogStream\",\"logs:PutLogEvents\"], \"Resource\": \"arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/route53/*\" }]}"
