AWSTemplateFormatVersion: "2010-09-09"
Description: "This is template for EC2"

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment for the project. dev by default.
    AllowedValues:
      - dev
      - prod

  EC2InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.nano
    Description: Enter t2.micro or t2.nano. Default is t2.micro.

Resources:
  EC2Instance01:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06c68f701d8090592
      InstanceType: !Ref EC2InstanceType

Rules:
  DevInstanceTypeRule:
    RuleCondition: !Equals
      - !Ref Environment
      - dev
    Assertions:
      - Assert:
          'Fn::Contains':
            - - t2.micro
            - !Ref EC2InstanceType
        AssertDescription: "For a test environment. Instance type must be 'micro'."
    